acks=all
bootstrap.servers=pkc-921jm.us-east-2.aws.confluent.cloud:9092
security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.username=L6ILRQYT4NMRR4BX
sasl.password=mSptuzVW9ERywkk+cdpZzxSWF0wgy9Sfv2Uf88TRphi7mf+KDLb43YC04/xb8Mvw

# Best practice for higher availability in librdkafka clients prior to 1.7
session.timeout.ms=45000

client.id=ccloud-python-client-960147b9-d733-4558-9871-0e5b6a7570d4
