# Cloud Topic Names Configuration
topic.user-activity=user-activity
topic.user-activity.partitions=3
topic.user-activity.replicas=3

topic.sensor-data=sensor-data
topic.sensor-data.partitions=3
topic.sensor-data.replicas=3
