[project]
name = "data-generator"
version = "0.1.0"
description = "Streaming data generator for Kafka (user activity + sensor data)"
requires-python = ">=3.11"
dependencies = [
    "confluent-kafka>=2.13.2",
    "faker>=40.23.0",
    "python-dateutil>=2.9.0",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
